2025-08-20 17:44:56 [ERROR]: Error loading command remind.ts: Cannot find module 'date-fns'
Require stack:
- /home/runner/workspace/src/commands/utility/remind.ts {
  "code": "MODULE_NOT_FOUND",
  "requireStack": [
    "/home/runner/workspace/src/commands/utility/remind.ts"
  ],
  "stack": "Error: Cannot find module 'date-fns'\nRequire stack:\n- /home/runner/workspace/src/commands/utility/remind.ts\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1212:15)\n    at nextResolveSimple (/home/runner/workspace/node_modules/tsx/dist/register-D46fvsV_.cjs:4:1004)\n    at /home/runner/workspace/node_modules/tsx/dist/register-D46fvsV_.cjs:3:2630\n    at /home/runner/workspace/node_modules/tsx/dist/register-D46fvsV_.cjs:3:1542\n    at resolveTsPaths (/home/runner/workspace/node_modules/tsx/dist/register-D46fvsV_.cjs:4:760)\n    at /home/runner/workspace/node_modules/tsx/dist/register-D46fvsV_.cjs:4:1102\n    at m._resolveFilename (file:///home/runner/workspace/node_modules/tsx/dist/register-B7jrtLTO.mjs:1:789)\n    at Module._load (node:internal/modules/cjs/loader:1043:27)\n    at Module.require (node:internal/modules/cjs/loader:1298:19)\n    at require (node:internal/modules/helpers:182:18)"
}
2025-08-20 17:45:56 [ERROR]: Error checking reminders: 
Invalid `this.prisma.reminder.findMany()` invocation in
/home/runner/workspace/src/utils/database.ts:111:39

  108 }
  109 
  110 public async getExpiredReminders() {
→ 111   return await this.prisma.reminder.findMany(
The table `main.reminders` does not exist in the current database. {
  "code": "P2021",
  "meta": {
    "modelName": "Reminder",
    "table": "main.reminders"
  },
  "clientVersion": "6.14.0",
  "name": "PrismaClientKnownRequestError",
  "stack": "PrismaClientKnownRequestError: \nInvalid `this.prisma.reminder.findMany()` invocation in\n/home/runner/workspace/src/utils/database.ts:111:39\n\n  108 }\n  109 \n  110 public async getExpiredReminders() {\n→ 111   return await this.prisma.reminder.findMany(\nThe table `main.reminders` does not exist in the current database.\n    at ei.handleRequestError (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:228:13)\n    at ei.handleAndLogRequestError (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:174:12)\n    at ei.request (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:143:12)\n    at async a (/home/runner/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:833:24)\n    at async DatabaseManager.getExpiredReminders (/home/runner/workspace/src/utils/database.ts:111:12)\n    at async checkReminders (/home/runner/workspace/src/services/reminderService.ts:8:30)\n    at async Timeout._onTimeout (/home/runner/workspace/src/events/ready.ts:16:9)"
}
2025-08-20 17:46:56 [ERROR]: Error checking reminders: 
Invalid `this.prisma.reminder.findMany()` invocation in
/home/runner/workspace/src/utils/database.ts:111:39

  108 }
  109 
  110 public async getExpiredReminders() {
→ 111   return await this.prisma.reminder.findMany(
The table `main.reminders` does not exist in the current database. {
  "code": "P2021",
  "meta": {
    "modelName": "Reminder",
    "table": "main.reminders"
  },
  "clientVersion": "6.14.0",
  "name": "PrismaClientKnownRequestError",
  "stack": "PrismaClientKnownRequestError: \nInvalid `this.prisma.reminder.findMany()` invocation in\n/home/runner/workspace/src/utils/database.ts:111:39\n\n  108 }\n  109 \n  110 public async getExpiredReminders() {\n→ 111   return await this.prisma.reminder.findMany(\nThe table `main.reminders` does not exist in the current database.\n    at ei.handleRequestError (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:228:13)\n    at ei.handleAndLogRequestError (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:174:12)\n    at ei.request (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:143:12)\n    at async a (/home/runner/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:833:24)\n    at async DatabaseManager.getExpiredReminders (/home/runner/workspace/src/utils/database.ts:111:12)\n    at async checkReminders (/home/runner/workspace/src/services/reminderService.ts:8:30)\n    at async Timeout._onTimeout (/home/runner/workspace/src/events/ready.ts:16:9)"
}
2025-08-20 17:47:56 [ERROR]: Error checking reminders: 
Invalid `this.prisma.reminder.findMany()` invocation in
/home/runner/workspace/src/utils/database.ts:111:39

  108 }
  109 
  110 public async getExpiredReminders() {
→ 111   return await this.prisma.reminder.findMany(
The table `main.reminders` does not exist in the current database. {
  "code": "P2021",
  "meta": {
    "modelName": "Reminder",
    "table": "main.reminders"
  },
  "clientVersion": "6.14.0",
  "name": "PrismaClientKnownRequestError",
  "stack": "PrismaClientKnownRequestError: \nInvalid `this.prisma.reminder.findMany()` invocation in\n/home/runner/workspace/src/utils/database.ts:111:39\n\n  108 }\n  109 \n  110 public async getExpiredReminders() {\n→ 111   return await this.prisma.reminder.findMany(\nThe table `main.reminders` does not exist in the current database.\n    at ei.handleRequestError (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:228:13)\n    at ei.handleAndLogRequestError (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:174:12)\n    at ei.request (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:143:12)\n    at async a (/home/runner/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:833:24)\n    at async DatabaseManager.getExpiredReminders (/home/runner/workspace/src/utils/database.ts:111:12)\n    at async checkReminders (/home/runner/workspace/src/services/reminderService.ts:8:30)\n    at async Timeout._onTimeout (/home/runner/workspace/src/events/ready.ts:16:9)"
}
2025-08-20 17:48:56 [ERROR]: Error checking reminders: 
Invalid `this.prisma.reminder.findMany()` invocation in
/home/runner/workspace/src/utils/database.ts:111:39

  108 }
  109 
  110 public async getExpiredReminders() {
→ 111   return await this.prisma.reminder.findMany(
The table `main.reminders` does not exist in the current database. {
  "code": "P2021",
  "meta": {
    "modelName": "Reminder",
    "table": "main.reminders"
  },
  "clientVersion": "6.14.0",
  "name": "PrismaClientKnownRequestError",
  "stack": "PrismaClientKnownRequestError: \nInvalid `this.prisma.reminder.findMany()` invocation in\n/home/runner/workspace/src/utils/database.ts:111:39\n\n  108 }\n  109 \n  110 public async getExpiredReminders() {\n→ 111   return await this.prisma.reminder.findMany(\nThe table `main.reminders` does not exist in the current database.\n    at ei.handleRequestError (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:228:13)\n    at ei.handleAndLogRequestError (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:174:12)\n    at ei.request (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:143:12)\n    at async a (/home/runner/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:833:24)\n    at async DatabaseManager.getExpiredReminders (/home/runner/workspace/src/utils/database.ts:111:12)\n    at async checkReminders (/home/runner/workspace/src/services/reminderService.ts:8:30)\n    at async Timeout._onTimeout (/home/runner/workspace/src/events/ready.ts:16:9)"
}
2025-08-20 17:49:56 [ERROR]: Error checking reminders: 
Invalid `this.prisma.reminder.findMany()` invocation in
/home/runner/workspace/src/utils/database.ts:111:39

  108 }
  109 
  110 public async getExpiredReminders() {
→ 111   return await this.prisma.reminder.findMany(
The table `main.reminders` does not exist in the current database. {
  "code": "P2021",
  "meta": {
    "modelName": "Reminder",
    "table": "main.reminders"
  },
  "clientVersion": "6.14.0",
  "name": "PrismaClientKnownRequestError",
  "stack": "PrismaClientKnownRequestError: \nInvalid `this.prisma.reminder.findMany()` invocation in\n/home/runner/workspace/src/utils/database.ts:111:39\n\n  108 }\n  109 \n  110 public async getExpiredReminders() {\n→ 111   return await this.prisma.reminder.findMany(\nThe table `main.reminders` does not exist in the current database.\n    at ei.handleRequestError (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:228:13)\n    at ei.handleAndLogRequestError (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:174:12)\n    at ei.request (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:143:12)\n    at async a (/home/runner/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:833:24)\n    at async DatabaseManager.getExpiredReminders (/home/runner/workspace/src/utils/database.ts:111:12)\n    at async checkReminders (/home/runner/workspace/src/services/reminderService.ts:8:30)\n    at async Timeout._onTimeout (/home/runner/workspace/src/events/ready.ts:16:9)"
}
2025-08-20 17:50:56 [ERROR]: Error checking reminders: 
Invalid `this.prisma.reminder.findMany()` invocation in
/home/runner/workspace/src/utils/database.ts:111:39

  108 }
  109 
  110 public async getExpiredReminders() {
→ 111   return await this.prisma.reminder.findMany(
The table `main.reminders` does not exist in the current database. {
  "code": "P2021",
  "meta": {
    "modelName": "Reminder",
    "table": "main.reminders"
  },
  "clientVersion": "6.14.0",
  "name": "PrismaClientKnownRequestError",
  "stack": "PrismaClientKnownRequestError: \nInvalid `this.prisma.reminder.findMany()` invocation in\n/home/runner/workspace/src/utils/database.ts:111:39\n\n  108 }\n  109 \n  110 public async getExpiredReminders() {\n→ 111   return await this.prisma.reminder.findMany(\nThe table `main.reminders` does not exist in the current database.\n    at ei.handleRequestError (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:228:13)\n    at ei.handleAndLogRequestError (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:174:12)\n    at ei.request (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:143:12)\n    at async a (/home/runner/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:833:24)\n    at async DatabaseManager.getExpiredReminders (/home/runner/workspace/src/utils/database.ts:111:12)\n    at async checkReminders (/home/runner/workspace/src/services/reminderService.ts:8:30)\n    at async Timeout._onTimeout (/home/runner/workspace/src/events/ready.ts:16:9)"
}
2025-08-20 17:51:56 [ERROR]: Error checking reminders: 
Invalid `this.prisma.reminder.findMany()` invocation in
/home/runner/workspace/src/utils/database.ts:111:39

  108 }
  109 
  110 public async getExpiredReminders() {
→ 111   return await this.prisma.reminder.findMany(
The table `main.reminders` does not exist in the current database. {
  "code": "P2021",
  "meta": {
    "modelName": "Reminder",
    "table": "main.reminders"
  },
  "clientVersion": "6.14.0",
  "name": "PrismaClientKnownRequestError",
  "stack": "PrismaClientKnownRequestError: \nInvalid `this.prisma.reminder.findMany()` invocation in\n/home/runner/workspace/src/utils/database.ts:111:39\n\n  108 }\n  109 \n  110 public async getExpiredReminders() {\n→ 111   return await this.prisma.reminder.findMany(\nThe table `main.reminders` does not exist in the current database.\n    at ei.handleRequestError (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:228:13)\n    at ei.handleAndLogRequestError (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:174:12)\n    at ei.request (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:143:12)\n    at async a (/home/runner/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:833:24)\n    at async DatabaseManager.getExpiredReminders (/home/runner/workspace/src/utils/database.ts:111:12)\n    at async checkReminders (/home/runner/workspace/src/services/reminderService.ts:8:30)\n    at async Timeout._onTimeout (/home/runner/workspace/src/events/ready.ts:16:9)"
}
2025-08-20 17:55:37 [ERROR]: Error loading command remind.ts: Cannot find module 'date-fns'
Require stack:
- /home/runner/workspace/src/commands/utility/remind.ts {
  "code": "MODULE_NOT_FOUND",
  "requireStack": [
    "/home/runner/workspace/src/commands/utility/remind.ts"
  ],
  "stack": "Error: Cannot find module 'date-fns'\nRequire stack:\n- /home/runner/workspace/src/commands/utility/remind.ts\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1212:15)\n    at nextResolveSimple (/home/runner/workspace/node_modules/tsx/dist/register-D46fvsV_.cjs:4:1004)\n    at /home/runner/workspace/node_modules/tsx/dist/register-D46fvsV_.cjs:3:2630\n    at /home/runner/workspace/node_modules/tsx/dist/register-D46fvsV_.cjs:3:1542\n    at resolveTsPaths (/home/runner/workspace/node_modules/tsx/dist/register-D46fvsV_.cjs:4:760)\n    at /home/runner/workspace/node_modules/tsx/dist/register-D46fvsV_.cjs:4:1102\n    at m._resolveFilename (file:///home/runner/workspace/node_modules/tsx/dist/register-B7jrtLTO.mjs:1:789)\n    at Module._load (node:internal/modules/cjs/loader:1043:27)\n    at Module.require (node:internal/modules/cjs/loader:1298:19)\n    at require (node:internal/modules/helpers:182:18)"
}
2025-08-20 17:56:37 [ERROR]: Error checking reminders: 
Invalid `this.prisma.reminder.findMany()` invocation in
/home/runner/workspace/src/utils/database.ts:111:39

  108 }
  109 
  110 public async getExpiredReminders() {
→ 111   return await this.prisma.reminder.findMany(
The table `main.reminders` does not exist in the current database. {
  "code": "P2021",
  "meta": {
    "modelName": "Reminder",
    "table": "main.reminders"
  },
  "clientVersion": "6.14.0",
  "name": "PrismaClientKnownRequestError",
  "stack": "PrismaClientKnownRequestError: \nInvalid `this.prisma.reminder.findMany()` invocation in\n/home/runner/workspace/src/utils/database.ts:111:39\n\n  108 }\n  109 \n  110 public async getExpiredReminders() {\n→ 111   return await this.prisma.reminder.findMany(\nThe table `main.reminders` does not exist in the current database.\n    at ei.handleRequestError (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:228:13)\n    at ei.handleAndLogRequestError (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:174:12)\n    at ei.request (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:143:12)\n    at async a (/home/runner/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:833:24)\n    at async DatabaseManager.getExpiredReminders (/home/runner/workspace/src/utils/database.ts:111:12)\n    at async checkReminders (/home/runner/workspace/src/services/reminderService.ts:8:30)\n    at async Timeout._onTimeout (/home/runner/workspace/src/events/ready.ts:16:9)"
}
2025-08-20 18:35:25 [ERROR]: Error loading command remind.ts: Cannot find module 'date-fns'
Require stack:
- /home/runner/workspace/src/commands/utility/remind.ts {
  "code": "MODULE_NOT_FOUND",
  "requireStack": [
    "/home/runner/workspace/src/commands/utility/remind.ts"
  ],
  "stack": "Error: Cannot find module 'date-fns'\nRequire stack:\n- /home/runner/workspace/src/commands/utility/remind.ts\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1212:15)\n    at nextResolveSimple (/home/runner/workspace/node_modules/tsx/dist/register-D46fvsV_.cjs:4:1004)\n    at /home/runner/workspace/node_modules/tsx/dist/register-D46fvsV_.cjs:3:2630\n    at /home/runner/workspace/node_modules/tsx/dist/register-D46fvsV_.cjs:3:1542\n    at resolveTsPaths (/home/runner/workspace/node_modules/tsx/dist/register-D46fvsV_.cjs:4:760)\n    at /home/runner/workspace/node_modules/tsx/dist/register-D46fvsV_.cjs:4:1102\n    at m._resolveFilename (file:///home/runner/workspace/node_modules/tsx/dist/register-B7jrtLTO.mjs:1:789)\n    at Module._load (node:internal/modules/cjs/loader:1043:27)\n    at Module.require (node:internal/modules/cjs/loader:1298:19)\n    at require (node:internal/modules/helpers:182:18)"
}
2025-08-20 18:36:25 [ERROR]: Error checking reminders: 
Invalid `this.prisma.reminder.findMany()` invocation in
/home/runner/workspace/src/utils/database.ts:111:39

  108 }
  109 
  110 public async getExpiredReminders() {
→ 111   return await this.prisma.reminder.findMany(
The table `main.reminders` does not exist in the current database. {
  "code": "P2021",
  "meta": {
    "modelName": "Reminder",
    "table": "main.reminders"
  },
  "clientVersion": "6.14.0",
  "name": "PrismaClientKnownRequestError",
  "stack": "PrismaClientKnownRequestError: \nInvalid `this.prisma.reminder.findMany()` invocation in\n/home/runner/workspace/src/utils/database.ts:111:39\n\n  108 }\n  109 \n  110 public async getExpiredReminders() {\n→ 111   return await this.prisma.reminder.findMany(\nThe table `main.reminders` does not exist in the current database.\n    at ei.handleRequestError (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:228:13)\n    at ei.handleAndLogRequestError (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:174:12)\n    at ei.request (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:143:12)\n    at async a (/home/runner/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:833:24)\n    at async DatabaseManager.getExpiredReminders (/home/runner/workspace/src/utils/database.ts:111:12)\n    at async checkReminders (/home/runner/workspace/src/services/reminderService.ts:8:30)\n    at async Timeout._onTimeout (/home/runner/workspace/src/events/ready.ts:16:9)"
}
2025-08-20 18:37:25 [ERROR]: Error checking reminders: 
Invalid `this.prisma.reminder.findMany()` invocation in
/home/runner/workspace/src/utils/database.ts:111:39

  108 }
  109 
  110 public async getExpiredReminders() {
→ 111   return await this.prisma.reminder.findMany(
The table `main.reminders` does not exist in the current database. {
  "code": "P2021",
  "meta": {
    "modelName": "Reminder",
    "table": "main.reminders"
  },
  "clientVersion": "6.14.0",
  "name": "PrismaClientKnownRequestError",
  "stack": "PrismaClientKnownRequestError: \nInvalid `this.prisma.reminder.findMany()` invocation in\n/home/runner/workspace/src/utils/database.ts:111:39\n\n  108 }\n  109 \n  110 public async getExpiredReminders() {\n→ 111   return await this.prisma.reminder.findMany(\nThe table `main.reminders` does not exist in the current database.\n    at ei.handleRequestError (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:228:13)\n    at ei.handleAndLogRequestError (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:174:12)\n    at ei.request (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:143:12)\n    at async a (/home/runner/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:833:24)\n    at async DatabaseManager.getExpiredReminders (/home/runner/workspace/src/utils/database.ts:111:12)\n    at async checkReminders (/home/runner/workspace/src/services/reminderService.ts:8:30)\n    at async Timeout._onTimeout (/home/runner/workspace/src/events/ready.ts:16:9)"
}
2025-08-20 18:38:25 [ERROR]: Error checking reminders: 
Invalid `this.prisma.reminder.findMany()` invocation in
/home/runner/workspace/src/utils/database.ts:111:39

  108 }
  109 
  110 public async getExpiredReminders() {
→ 111   return await this.prisma.reminder.findMany(
The table `main.reminders` does not exist in the current database. {
  "code": "P2021",
  "meta": {
    "modelName": "Reminder",
    "table": "main.reminders"
  },
  "clientVersion": "6.14.0",
  "name": "PrismaClientKnownRequestError",
  "stack": "PrismaClientKnownRequestError: \nInvalid `this.prisma.reminder.findMany()` invocation in\n/home/runner/workspace/src/utils/database.ts:111:39\n\n  108 }\n  109 \n  110 public async getExpiredReminders() {\n→ 111   return await this.prisma.reminder.findMany(\nThe table `main.reminders` does not exist in the current database.\n    at ei.handleRequestError (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:228:13)\n    at ei.handleAndLogRequestError (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:174:12)\n    at ei.request (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:143:12)\n    at async a (/home/runner/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:833:24)\n    at async DatabaseManager.getExpiredReminders (/home/runner/workspace/src/utils/database.ts:111:12)\n    at async checkReminders (/home/runner/workspace/src/services/reminderService.ts:8:30)\n    at async Timeout._onTimeout (/home/runner/workspace/src/events/ready.ts:16:9)"
}
2025-08-20 18:41:40 [ERROR]: Error checking reminders: 
Invalid `this.prisma.reminder.findMany()` invocation in
/home/runner/workspace/src/utils/database.ts:111:39

  108 }
  109 
  110 public async getExpiredReminders() {
→ 111   return await this.prisma.reminder.findMany(
The table `main.reminders` does not exist in the current database. {
  "code": "P2021",
  "meta": {
    "modelName": "Reminder",
    "table": "main.reminders"
  },
  "clientVersion": "6.14.0",
  "name": "PrismaClientKnownRequestError",
  "stack": "PrismaClientKnownRequestError: \nInvalid `this.prisma.reminder.findMany()` invocation in\n/home/runner/workspace/src/utils/database.ts:111:39\n\n  108 }\n  109 \n  110 public async getExpiredReminders() {\n→ 111   return await this.prisma.reminder.findMany(\nThe table `main.reminders` does not exist in the current database.\n    at ei.handleRequestError (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:228:13)\n    at ei.handleAndLogRequestError (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:174:12)\n    at ei.request (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:143:12)\n    at async a (/home/runner/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:833:24)\n    at async DatabaseManager.getExpiredReminders (/home/runner/workspace/src/utils/database.ts:111:12)\n    at async checkReminders (/home/runner/workspace/src/services/reminderService.ts:8:30)\n    at async Timeout._onTimeout (/home/runner/workspace/src/events/ready.ts:16:9)"
}
2025-08-20 18:42:40 [ERROR]: Error checking reminders: 
Invalid `this.prisma.reminder.findMany()` invocation in
/home/runner/workspace/src/utils/database.ts:111:39

  108 }
  109 
  110 public async getExpiredReminders() {
→ 111   return await this.prisma.reminder.findMany(
The table `main.reminders` does not exist in the current database. {
  "code": "P2021",
  "meta": {
    "modelName": "Reminder",
    "table": "main.reminders"
  },
  "clientVersion": "6.14.0",
  "name": "PrismaClientKnownRequestError",
  "stack": "PrismaClientKnownRequestError: \nInvalid `this.prisma.reminder.findMany()` invocation in\n/home/runner/workspace/src/utils/database.ts:111:39\n\n  108 }\n  109 \n  110 public async getExpiredReminders() {\n→ 111   return await this.prisma.reminder.findMany(\nThe table `main.reminders` does not exist in the current database.\n    at ei.handleRequestError (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:228:13)\n    at ei.handleAndLogRequestError (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:174:12)\n    at ei.request (/home/runner/workspace/node_modules/@prisma/client/src/runtime/RequestHandler.ts:143:12)\n    at async a (/home/runner/workspace/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:833:24)\n    at async DatabaseManager.getExpiredReminders (/home/runner/workspace/src/utils/database.ts:111:12)\n    at async checkReminders (/home/runner/workspace/src/services/reminderService.ts:8:30)\n    at async Timeout._onTimeout (/home/runner/workspace/src/events/ready.ts:16:9)"
}
2025-08-20 19:00:10 [ERROR]: Error executing prefix command deploy: Cannot edit a message authored by another user {
  "requestBody": {
    "files": [],
    "json": {
      "content": "<:deny:868562165093777468> Failed to deploy commands. Check console for details.",
      "tts": false,
      "enforce_nonce": false
    }
  },
  "rawError": {
    "message": "Cannot edit a message authored by another user",
    "code": 50005
  },
  "code": 50005,
  "status": 403,
  "method": "PATCH",
  "url": "https://discord.com/api/v10/channels/1407113687633756304/messages/1407801397818298438",
  "stack": "DiscordAPIError[50005]: Cannot edit a message authored by another user\n    at handleErrors (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:148:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async SequentialHandler.runRequest (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:417:20)\n    at async SequentialHandler.queueRequest (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:169:11)\n    at async _REST.request (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/REST.ts:210:20)\n    at async GuildMessageManager.edit (/home/runner/workspace/node_modules/discord.js/src/managers/MessageManager.js:188:15)\n    at async Object.execute (/home/runner/workspace/src/commands/admin/deploy.ts:100:7)\n    at async BleedClient.execute (/home/runner/workspace/src/events/messageCreate.ts:118:7)"
}
2025-08-20 19:00:34 [ERROR]: Error executing prefix command deploy: Cannot edit a message authored by another user {
  "requestBody": {
    "files": [],
    "json": {
      "content": "<:deny:868562165093777468> Failed to deploy commands. Check console for details.",
      "tts": false,
      "enforce_nonce": false
    }
  },
  "rawError": {
    "message": "Cannot edit a message authored by another user",
    "code": 50005
  },
  "code": 50005,
  "status": 403,
  "method": "PATCH",
  "url": "https://discord.com/api/v10/channels/1407113687633756304/messages/1407801501170270331",
  "stack": "DiscordAPIError[50005]: Cannot edit a message authored by another user\n    at handleErrors (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:148:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async SequentialHandler.runRequest (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:417:20)\n    at async SequentialHandler.queueRequest (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:169:11)\n    at async _REST.request (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/REST.ts:210:20)\n    at async GuildMessageManager.edit (/home/runner/workspace/node_modules/discord.js/src/managers/MessageManager.js:188:15)\n    at async Object.execute (/home/runner/workspace/src/commands/admin/deploy.ts:100:7)\n    at async BleedClient.execute (/home/runner/workspace/src/events/messageCreate.ts:118:7)"
}
2025-08-20 19:01:22 [ERROR]: Error executing prefix command deploy: Cannot edit a message authored by another user {
  "requestBody": {
    "files": [],
    "json": {
      "content": "<:deny:868562165093777468> Failed to deploy commands. Check console for details.",
      "tts": false,
      "enforce_nonce": false
    }
  },
  "rawError": {
    "message": "Cannot edit a message authored by another user",
    "code": 50005
  },
  "code": 50005,
  "status": 403,
  "method": "PATCH",
  "url": "https://discord.com/api/v10/channels/1407113687633756304/messages/1407801702492672082",
  "stack": "DiscordAPIError[50005]: Cannot edit a message authored by another user\n    at handleErrors (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:148:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async SequentialHandler.runRequest (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:417:20)\n    at async SequentialHandler.queueRequest (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:169:11)\n    at async _REST.request (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/REST.ts:210:20)\n    at async GuildMessageManager.edit (/home/runner/workspace/node_modules/discord.js/src/managers/MessageManager.js:188:15)\n    at async Object.execute (/home/runner/workspace/src/commands/admin/deploy.ts:100:7)\n    at async BleedClient.execute (/home/runner/workspace/src/events/messageCreate.ts:118:7)"
}
2025-08-20 19:01:55 [ERROR]: Error executing prefix command deploy: Cannot edit a message authored by another user {
  "requestBody": {
    "files": [],
    "json": {
      "content": "<:deny:868562165093777468> Failed to deploy commands. Check console for details.",
      "tts": false,
      "enforce_nonce": false
    }
  },
  "rawError": {
    "message": "Cannot edit a message authored by another user",
    "code": 50005
  },
  "code": 50005,
  "status": 403,
  "method": "PATCH",
  "url": "https://discord.com/api/v10/channels/1405612757121765530/messages/1407801841709879459",
  "stack": "DiscordAPIError[50005]: Cannot edit a message authored by another user\n    at handleErrors (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:148:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async SequentialHandler.runRequest (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:417:20)\n    at async SequentialHandler.queueRequest (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:169:11)\n    at async _REST.request (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/REST.ts:210:20)\n    at async GuildMessageManager.edit (/home/runner/workspace/node_modules/discord.js/src/managers/MessageManager.js:188:15)\n    at async Object.execute (/home/runner/workspace/src/commands/admin/deploy.ts:100:7)\n    at async BleedClient.execute (/home/runner/workspace/src/events/messageCreate.ts:118:7)"
}
2025-08-20 19:02:11 [ERROR]: Error executing prefix command deploy: Cannot edit a message authored by another user {
  "requestBody": {
    "files": [],
    "json": {
      "content": "<:deny:868562165093777468> Failed to deploy commands. Check console for details.",
      "tts": false,
      "enforce_nonce": false
    }
  },
  "rawError": {
    "message": "Cannot edit a message authored by another user",
    "code": 50005
  },
  "code": 50005,
  "status": 403,
  "method": "PATCH",
  "url": "https://discord.com/api/v10/channels/1136367366016610438/messages/1407801908529201304",
  "stack": "DiscordAPIError[50005]: Cannot edit a message authored by another user\n    at handleErrors (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:148:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async SequentialHandler.runRequest (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:417:20)\n    at async SequentialHandler.queueRequest (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:169:11)\n    at async _REST.request (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/REST.ts:210:20)\n    at async GuildMessageManager.edit (/home/runner/workspace/node_modules/discord.js/src/managers/MessageManager.js:188:15)\n    at async Object.execute (/home/runner/workspace/src/commands/admin/deploy.ts:100:7)\n    at async BleedClient.execute (/home/runner/workspace/src/events/messageCreate.ts:118:7)"
}
2025-08-20 19:02:55 [ERROR]: Error executing prefix command deploy: Cannot edit a message authored by another user {
  "requestBody": {
    "files": [],
    "json": {
      "content": "<:deny:868562165093777468> Failed to deploy commands. Check console for details.",
      "tts": false,
      "enforce_nonce": false
    }
  },
  "rawError": {
    "message": "Cannot edit a message authored by another user",
    "code": 50005
  },
  "code": 50005,
  "status": 403,
  "method": "PATCH",
  "url": "https://discord.com/api/v10/channels/1136367366016610438/messages/1407801962229137610",
  "stack": "DiscordAPIError[50005]: Cannot edit a message authored by another user\n    at handleErrors (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:148:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async SequentialHandler.runRequest (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:417:20)\n    at async SequentialHandler.queueRequest (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:169:11)\n    at async _REST.request (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/REST.ts:210:20)\n    at async GuildMessageManager.edit (/home/runner/workspace/node_modules/discord.js/src/managers/MessageManager.js:188:15)\n    at async Object.execute (/home/runner/workspace/src/commands/admin/deploy.ts:100:7)\n    at async BleedClient.execute (/home/runner/workspace/src/events/messageCreate.ts:118:7)"
}
2025-08-20 19:05:51 [ERROR]: Error executing prefix command deploy: Cannot edit a message authored by another user {
  "requestBody": {
    "files": [],
    "json": {
      "content": "<:deny:868562165093777468> Failed to deploy commands. Check console for details.",
      "tts": false,
      "enforce_nonce": false
    }
  },
  "rawError": {
    "message": "Cannot edit a message authored by another user",
    "code": 50005
  },
  "code": 50005,
  "status": 403,
  "method": "PATCH",
  "url": "https://discord.com/api/v10/channels/1407301207457923085/messages/1407802830051475528",
  "stack": "DiscordAPIError[50005]: Cannot edit a message authored by another user\n    at handleErrors (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:148:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async SequentialHandler.runRequest (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:417:20)\n    at async SequentialHandler.queueRequest (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:169:11)\n    at async _REST.request (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/REST.ts:210:20)\n    at async GuildMessageManager.edit (/home/runner/workspace/node_modules/discord.js/src/managers/MessageManager.js:188:15)\n    at async Object.execute (/home/runner/workspace/src/commands/admin/deploy.ts:100:7)\n    at async BleedClient.execute (/home/runner/workspace/src/events/messageCreate.ts:118:7)"
}
2025-08-20 19:06:00 [ERROR]: Error executing prefix command deploy: Cannot edit a message authored by another user {
  "requestBody": {
    "files": [],
    "json": {
      "content": "<:deny:868562165093777468> Failed to deploy commands. Check console for details.",
      "tts": false,
      "enforce_nonce": false
    }
  },
  "rawError": {
    "message": "Cannot edit a message authored by another user",
    "code": 50005
  },
  "code": 50005,
  "status": 403,
  "method": "PATCH",
  "url": "https://discord.com/api/v10/channels/1407301207457923085/messages/1407802856089849866",
  "stack": "DiscordAPIError[50005]: Cannot edit a message authored by another user\n    at handleErrors (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:148:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async SequentialHandler.runRequest (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:417:20)\n    at async SequentialHandler.queueRequest (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:169:11)\n    at async _REST.request (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/REST.ts:210:20)\n    at async GuildMessageManager.edit (/home/runner/workspace/node_modules/discord.js/src/managers/MessageManager.js:188:15)\n    at async Object.execute (/home/runner/workspace/src/commands/admin/deploy.ts:100:7)\n    at async BleedClient.execute (/home/runner/workspace/src/events/messageCreate.ts:118:7)"
}
2025-08-20 19:06:51 [ERROR]: Error executing prefix command deploy: Cannot edit a message authored by another user {
  "requestBody": {
    "files": [],
    "json": {
      "content": "<:deny:868562165093777468> Failed to deploy commands. Check console for details.",
      "tts": false,
      "enforce_nonce": false
    }
  },
  "rawError": {
    "message": "Cannot edit a message authored by another user",
    "code": 50005
  },
  "code": 50005,
  "status": 403,
  "method": "PATCH",
  "url": "https://discord.com/api/v10/channels/1407301207457923085/messages/1407802901899903098",
  "stack": "DiscordAPIError[50005]: Cannot edit a message authored by another user\n    at handleErrors (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:148:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async SequentialHandler.runRequest (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:417:20)\n    at async SequentialHandler.queueRequest (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:169:11)\n    at async _REST.request (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/REST.ts:210:20)\n    at async GuildMessageManager.edit (/home/runner/workspace/node_modules/discord.js/src/managers/MessageManager.js:188:15)\n    at async Object.execute (/home/runner/workspace/src/commands/admin/deploy.ts:100:7)\n    at async BleedClient.execute (/home/runner/workspace/src/events/messageCreate.ts:118:7)"
}
2025-08-20 19:11:41 [ERROR]: Error executing prefix command deploy: Cannot edit a message authored by another user {
  "requestBody": {
    "files": [],
    "json": {
      "content": "<:deny:868562165093777468> Failed to deploy commands. Check console for details.",
      "tts": false,
      "enforce_nonce": false
    }
  },
  "rawError": {
    "message": "Cannot edit a message authored by another user",
    "code": 50005
  },
  "code": 50005,
  "status": 403,
  "method": "PATCH",
  "url": "https://discord.com/api/v10/channels/1407113687633756304/messages/1407804298644951071",
  "stack": "DiscordAPIError[50005]: Cannot edit a message authored by another user\n    at handleErrors (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:148:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async SequentialHandler.runRequest (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:417:20)\n    at async SequentialHandler.queueRequest (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:169:11)\n    at async _REST.request (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/REST.ts:210:20)\n    at async GuildMessageManager.edit (/home/runner/workspace/node_modules/discord.js/src/managers/MessageManager.js:188:15)\n    at async Object.execute (/home/runner/workspace/src/commands/admin/deploy.ts:100:7)\n    at async BleedClient.execute (/home/runner/workspace/src/events/messageCreate.ts:118:7)"
}
2025-08-20 19:11:46 [ERROR]: Error executing prefix command deploy: Cannot edit a message authored by another user {
  "requestBody": {
    "files": [],
    "json": {
      "content": "<:deny:868562165093777468> Failed to deploy commands. Check console for details.",
      "tts": false,
      "enforce_nonce": false
    }
  },
  "rawError": {
    "message": "Cannot edit a message authored by another user",
    "code": 50005
  },
  "code": 50005,
  "status": 403,
  "method": "PATCH",
  "url": "https://discord.com/api/v10/channels/1407113687633756304/messages/1407804318609969307",
  "stack": "DiscordAPIError[50005]: Cannot edit a message authored by another user\n    at handleErrors (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:148:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async SequentialHandler.runRequest (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:417:20)\n    at async SequentialHandler.queueRequest (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:169:11)\n    at async _REST.request (/home/runner/workspace/node_modules/@discordjs/rest/src/lib/REST.ts:210:20)\n    at async GuildMessageManager.edit (/home/runner/workspace/node_modules/discord.js/src/managers/MessageManager.js:188:15)\n    at async Object.execute (/home/runner/workspace/src/commands/admin/deploy.ts:100:7)\n    at async BleedClient.execute (/home/runner/workspace/src/events/messageCreate.ts:118:7)"
}
2025-08-20 19:11:53 [ERROR]: Error executing command voicemaster: No subcommand specified for interaction. {
  "code": "CommandInteractionOptionNoSubcommand",
  "stack": "TypeError [CommandInteractionOptionNoSubcommand]: No subcommand specified for interaction.\n    at CommandInteractionOptionResolver.getSubcommand (/home/runner/workspace/node_modules/discord.js/src/structures/CommandInteractionOptionResolver.js:113:13)\n    at Object.execute (/home/runner/workspace/src/commands/server/voicemaster.ts:44:44)\n    at BleedClient.execute (/home/runner/workspace/src/events/interactionCreate.ts:86:23)\n    at BleedClient.emit (node:events:524:28)\n    at InteractionCreateAction.handle (/home/runner/workspace/node_modules/discord.js/src/client/actions/InteractionCreate.js:101:12)\n    at module.exports [as INTERACTION_CREATE] (/home/runner/workspace/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)\n    at WebSocketManager.handlePacket (/home/runner/workspace/node_modules/discord.js/src/client/websocket/WebSocketManager.js:351:31)\n    at WebSocketManager.<anonymous> (/home/runner/workspace/node_modules/discord.js/src/client/websocket/WebSocketManager.js:235:12)\n    at WebSocketManager.emit (/home/runner/workspace/node_modules/@vladfrangu/async_event_emitter/src/index.ts:513:28)\n    at WebSocketShard.<anonymous> (/home/runner/workspace/node_modules/@discordjs/ws/src/strategies/sharding/SimpleShardingStrategy.ts:32:47)"
}
2025-08-20 19:14:13 [ERROR]: Error loading command voicemaster.ts: Transform failed with 1 error:
/home/runner/workspace/src/commands/server/voicemaster.ts:210:3: ERROR: Unexpected "," {
  "name": "TransformError",
  "stack": "Error: Transform failed with 1 error:\n/home/runner/workspace/src/commands/server/voicemaster.ts:210:3: ERROR: Unexpected \",\"\n    at failureErrorWithLog (/home/runner/workspace/node_modules/esbuild/lib/main.js:1467:15)\n    at /home/runner/workspace/node_modules/esbuild/lib/main.js:736:50\n    at responseCallbacks.<computed> (/home/runner/workspace/node_modules/esbuild/lib/main.js:603:9)\n    at handleIncomingPacket (/home/runner/workspace/node_modules/esbuild/lib/main.js:658:12)\n    at Socket.readFromStdout (/home/runner/workspace/node_modules/esbuild/lib/main.js:581:7)\n    at Socket.emit (node:events:524:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Readable.push (node:internal/streams/readable:392:5)\n    at Pipe.onStreamRead (node:internal/stream_base_commons:191:23)"
}
